# Generated by Django 4.0.6 on 2022-08-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipes_author_alter_recipes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cover',
            field=models.ImageField(blank=True, upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
