# Generated by Django 4.0.6 on 2022-08-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipes_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
