# Generated by Django 4.0.6 on 2022-08-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipes_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
